### ISSUE TITLE
Can't install on Visual Studio for Mac 2019

### ISSUE THREAD

**Issue by Kamilton** [ademanuele/VSMac-CodeCoverage#1]
On my VS4Mac 2019 installation MonoDevelop.Core and MonoDevelop.Idle versions are higher than supported by extension. Could You please update it?

<img width="277" alt="Zrzut ekranu 2019-04-20 o 23 29 49" src="https://user-images.githubusercontent.com/6454607/56462505-7e95d800-63c4-11e9-9468-b77874abacbd.png">

**Comment by ademanuele** [comment]
Yes. Will update within the next few days.

**Comment by ademanuele** [comment]
This is turning out to be a longer task than first expected.
Looks like Microsoft added some new APIs for interacting with the editor and will need some extra work to make it compatible with this.

**Comment by scoorey** [comment]
Thanks for working on this, we have the same issue. Is there a workaround to use the command line or something to spit out a code coverage report in the meantime?

**Comment by JFMG** [comment]
@ademanuele Thanks for the extension! Do you have any news for the fix or do you need help with a fix?

**Comment by ademanuele** [comment]
Hi,

I have not had the time to work on this for a while. Been pretty busy. Pull
Requests are always welcome 😃

**Comment by ademanuele** [comment]
Update:

Currently working on a new version of the extension to support the new Visual Studio editor.
Stay tuned for updates.

**Comment by ademanuele** [comment]
This issue should be resolved with the latest version of the extension.

**Comment by JFMG** [comment]
Thank you very much @ademanuele! I've just installed it and it works like a charm :-)
