### ISSUE TITLE
Unable to install with newer versions of dependencies

### ISSUE THREAD

**Issue by sleeke** [ademanuele/VSMac-CodeCoverage#2]
When I try to install, I receive the error:
<img width="424" alt="Screen Shot 2019-10-04 at 2 58 58 PM" src="https://user-images.githubusercontent.com/1614828/66242929-879b0d00-e6b7-11e9-986a-cc9d57e62a6c.png">

**Comment by ademanuele** [comment]
This issue should be resolved with the latest version of the extension.
