### ISSUE TITLE
Update to latest VS4Mac

### ISSUE THREAD

**Issue by wcoder** [ademanuele/VSMac-CodeCoverage#5]
Hi, thank you for the extension!

Could you please update the extension to support the latest stable Visual Studio for Mac?
```
Version 8.5 (build 3183)
```

Installation process:
<img width="436" alt="Screen Shot 2020-03-25 at 11 04 35 PM" src="https://user-images.githubusercontent.com/766193/77580616-5e806a00-6eed-11ea-9d72-020b7ab13b51.png">

**Comment by ademanuele** [comment]
Just released an update for this.

Check it out and see if it resolves your issue.

**Comment by arambrosius** [comment]
I am still getting these issues.

![Screenshot 2020-03-27 10 14 12](https://user-images.githubusercontent.com/35042830/77770833-e06ab300-7013-11ea-9a48-821a18d5b551.png)

**Comment by wcoder** [comment]
> Just released an update for this.
> 
> Check it out and see if it resolves your issue.

@ademanuele 
Yes, 2.0.1-alpha install successfully. Thanks!

@arambrosius looks as you are used old version Visual Studio

**Comment by arambrosius** [comment]
@wcoder I believe I am on a newer version of Visual Studio. I am on v8.5 when it is looking for 7.2.2

**Comment by ademanuele** [comment]
> I am still getting these issues.
> 
> ![Screenshot 2020-03-27 10 14 12](https://user-images.githubusercontent.com/35042830/77770833-e06ab300-7013-11ea-9a48-821a18d5b551.png)

@arambrosius this screenshot seems to suggest that its failing to update the `MonoDevelop.XUnit.MonoDevelop.XUnit2.0.7.15` extension rather than the Code Coverage extension.

**Comment by jbachelor** [comment]
First and foremost, thank you SO much @ademanuele for this fantastic tool... I had my own coverage script going on the command line, but it was cumbersome and not integrated with the IDE at all. I've just installed your extension (v2.0.1), and it's working wonderfully.

To provide another datapoint on this particular issue, I had no problems installing the extension. Below are the details for my VS4Mac install. 

_Thanks again!!_
***
=== Visual Studio Community 2019 for Mac ===

Version 8.5.1 (build 42)
Installation UUID: d26f5600-5ca0-4038-83c7-01bbd1088d12
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.14.1.39 (d16-5 / 30e8706b4)

	Package version: 608000099

=== Mono Framework MDK ===

Runtime:
	Mono 6.8.0.99 (2019-10/1182f8cbf5b) (64-bit)
	Package version: 608000099

=== Roslyn (Language Service) ===

3.5.0-beta4-20125-04+1baa0b3063238ed752ad1f0368b1df6b6901373e

=== NuGet ===

Version: 5.4.0.6315

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.200/Sdks
SDK Versions:
	3.1.200
	3.1.102
	3.1.101
	3.1.100
	3.0.101
	3.0.100
	2.1.701
	2.1.700
	2.1.505
	2.1.504
	2.1.503
	2.1.302
	2.1.301
	2.1.103
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.2
	3.1.1
	3.1.0
	3.0.1
	3.0.0
	2.1.16
	2.1.15
	2.1.14
	2.1.13
	2.1.12
	2.1.11
	2.1.9
	2.1.8
	2.1.7
	2.1.2
	2.1.1
	2.0.6
	2.0.5

=== Xamarin.Profiler ===

Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin Designer ===

Version: 16.5.0.471
Hash: 35aa4889d
Branch: remotes/origin/d16-5
Build date: 2020-02-25 00:52:08 UTC

=== Xamarin.Android ===

Version: 10.2.0.100 (Visual Studio Community)
Commit: xamarin-android/d16-5/988c811
Android SDK: /Users/jbachelor/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.5
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: c0c5c78
Java.Interop: xamarin/java.interop/d16-5@fc18c54
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.28.0@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-5@9f4ed4b

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/jbachelor/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.5.0.39
Hash: 6fb4c79
Branch: remotes/origin/d16-5
Build date: 2020-03-28 00:48:52 UTC

=== Android Device Manager ===

Version: 16.5.0.71
Hash: 49194e8
Branch: remotes/origin/d16-5~1
Build date: 2020-03-28 00:49:12 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 11.4 (16134)
Build 11E146

=== Xamarin.Mac ===

Version: 6.16.0.11 (Visual Studio Community)
Hash: aa73e4125
Branch: d16-5-xcode11.4
Build date: 2020-03-25 11:04:02-0400

=== Xamarin.iOS ===

Version: 13.16.0.11 (Visual Studio Community)
Hash: aa73e4125
Branch: d16-5-xcode11.4
Build date: 2020-03-25 11:04:03-0400

=== Build Information ===

Release ID: 805010042
Git revision: 926c6e86370a6d68fc930f0600932e0a9192e3da
Build date: 2020-03-30 17:14:37-04
Build branch: release-8.5
Xamarin extensions: 926c6e86370a6d68fc930f0600932e0a9192e3da

=== Operating System ===

Mac OS X 10.15.4
Darwin 19.4.0 Darwin Kernel Version 19.4.0
    Wed Mar  4 22:28:40 PST 2020
    root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Template Creator 0.5
Code Coverage 2.0.1-alpha
MvvmCross Template pack 2.1.0

**Comment by ademanuele** [comment]
Thanks for the feedback @jbachelor. Glad you're enjoying the extension. 😄

That being the case, I will consider this issue closed.
